stages:
- name: first_stage
  dependencies: []
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      message: "a new dawn"
      inputfile:  'global://public0001.dat'
      outputfile: 'local://{workdir}/outputfile.txt'
    step: {$ref: 'steps.yml#/step'}
- name: second_state
  dependencies: [first_stage]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      message: "with a new message"
      inputfile:  {stages: first_stage, output: outputfile, unwrap: true}
      outputfile: 'local://{workdir}/outputfile.txt'
    step: {$ref: 'steps.yml#/step'}
